name: "Build database file and deploy"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1-5" # during work hours

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    name: "Build and Deploy"
    runs-on: "ubuntu-22.04"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout main branch test version
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Run the builder
        run: python build.py

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Workflow"
          git add src/database/repos.json repos.md repos_html.md -f
          git diff --quiet --cached || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit the database file
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git commit -m "Generate new database"
          git push

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        if: steps.verify_diff.outputs.changed == 'true'
        id: deployment
        uses: actions/deploy-pages@v1
